// <auto-generated />
using System;
using Infrastructure.Persistence.Pg;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Pg.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231206135000_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Core.Entities.Persone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.ToTable("Persones");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1c17088-cc68-4a86-8ede-a5b27a13e3c3"),
                            Age = 18,
                            City = "Moscow",
                            Country = "Russia",
                            Name = "Alex"
                        },
                        new
                        {
                            Id = new Guid("f51df220-6eed-440f-b40e-1bf0aea39149"),
                            Age = 28,
                            City = "Bermangham",
                            Country = "England",
                            Name = "Peter"
                        },
                        new
                        {
                            Id = new Guid("dffee042-a984-4ebd-951d-f4ed6c2de973"),
                            Age = 58,
                            City = "Washington",
                            Country = "USA",
                            Name = "Jone"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
