// <auto-generated />
using System;
using Infrastucture.DataAccess.Pg;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastucture.DataAccess.Pg.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240629145202_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("1cd2133d-4c3c-4b01-915b-86c0a6132070"),
                            Cost = 562m,
                            Count = 10,
                            CreateTime = new DateTime(2024, 6, 29, 14, 52, 1, 671, DateTimeKind.Utc).AddTicks(6153),
                            Name = "Product 1"
                        },
                        new
                        {
                            ProductId = new Guid("b2dd5f28-9c94-4e69-9e51-2b467793de6b"),
                            Cost = 4158m,
                            Count = 100,
                            CreateTime = new DateTime(2024, 6, 29, 14, 52, 1, 671, DateTimeKind.Utc).AddTicks(6160),
                            Name = "Product 2"
                        },
                        new
                        {
                            ProductId = new Guid("57adef7d-7322-473a-9a34-a0381f2991ba"),
                            Cost = 25m,
                            Count = 5469,
                            CreateTime = new DateTime(2024, 6, 29, 14, 52, 1, 671, DateTimeKind.Utc).AddTicks(6162),
                            Name = "Product 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
