@HostAddress = http://localhost:5014
@JwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidG9tQGdtYWlsLmNvbSIsImV4cCI6MTc0NTA2NDM1MywiaXNzIjoiTXlBdXRoU2VydmVyIiwiYXVkIjoiTXlBdXRoQ2xpZW50In0.EBCMmZS5k2vqI_KCUzEPDlZS7XXBSJiNGVPL17gxU5Q


### 1. Сначала получаем токен
POST {{HostAddress}}/jwt
Accept: application/json
Content-Type: application/json


### jwt endpoint

GET {{HostAddress}}/hello_jwt/
Accept: application/json
Authorization: Bearer {{JwtToken}}


###

